---
title: "Eda Metadata"
output:
  html_document:
    df_print: paged
---

```{r, echo = T, results = 'hide', warning=FALSE, include=FALSE}
# Load Dataset
source("../utils.R")
data <- read_csv("../data/metadata.csv")
```


```{r}
data %>% dplyr::count(idCountry) %>% 
  ggplot(aes(x=reorder(idCountry,n), y=n)) + 
  geom_bar(stat="identity", position=position_dodge())+
  ggtitle("Bases de Datos por País") +
  scale_fill_brewer(palette="Paired") +
  coord_flip()+
  theme_minimal() + xlab("Número de Bases de Datos") + 
  ylab("País")
```


```{r}
data %>% dplyr::count(gYear) %>% 
  ggplot(aes(x=gYear, y=n)) + 
  geom_point(color = "steelblue")+
  scale_fill_brewer(palette="Paired") +
  theme_minimal() +
  ggtitle("Número de Bases de Datos por Año") + 
  xlab("Años") + 
  ylab("Número de Bases de Datos")
```

```{r}
tmp <- data %>% group_by(idCountry) %>% 
    mutate(countT= n()) %>%
    group_by(gYear, add=TRUE) %>%
    dplyr::summarize(n = n(),
                     countT = min(countT)) %>% 
  mutate(pecentage=round(100*n/countT,2))

tmp %>% ggplot() + geom_bar(aes(y = pecentage, x = idCountry,
                                      fill = as_factor(gYear)),stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+ 
  ggtitle("Porcentaje de Bases de Datos por Año - País") + 
  xlab("País") + 
  ylab("Porcentaje")  



```

```{r}
data %>% dplyr::count(study_type) %>% 
  ggplot(aes(x=reorder(study_type,n), y=n)) + 
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_brewer(palette="Paired") +
  coord_flip()+
  theme_minimal() + 
  ggtitle("Número de Bases de Datos por Tipo de Estudio") + 
  xlab("Número de Bases de Datos") + 
  ylab("Tipo de Estudio")  

```

